---

# Ansible Requirements File
# https://docs.ansible.com/ansible/galaxy.html#advanced-control-over-role-requirements-files
#
# Install via: ansible-galaxy install -r requirements.yml

- src: https://github.com/ridingbytes/ridingbytes.ansible-base.git
  version: master

- src: https://github.com/ridingbytes/ridingbytes.ansible-security.git
  version: master
