---

- hosts: all
  become: yes
  gather_facts: yes
  pre_tasks:
    - name: Include Vagrant Variables `vagrant_configure.yml`
      include_vars: vagrant_configure.yml
      tags:
        - always

  roles:
    - ridingbytes.ansible-base-role
    - ridingbytes.ansible-security-role
    - ridingbytes.ansible-postgresql-role
